DROP TABLE IF EXISTS `TagTodo`;
DROP TABLE  IF EXISTS `Todo`;
DROP TABLE IF EXISTS `Tag`;
DROP PROCEDURE IF EXISTS `AddTagIfNotExist`;
DROP PROCEDURE IF EXISTS `AddTagTodoIfNotExist`;
DROP PROCEDURE IF EXISTS `ReOrderTodo`;