version: '3.7'

services:
  db:
    container_name: "todos_db"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - golang_test
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    # setting some env vars to create the DB
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "todos"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret"

    # we mount a data volume to make sure we don't lose data
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  grpc:
    container_name:  "grpc"
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: service.Dockerfile
    ports:
      - "4040:4040"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "todos"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret"
    # we are depending on the mysql backend
    depends_on:
      - db
    # We mount the working dir into the container, handy for development
    # This is what makes the hot reloading work inside of a Docker container
    volumes:
      - .:/app/
    networks:
      - golang_test

networks:
  golang_test:
volumes:
  mysql_data: