version: '3.7'

services:
  db:
    container_name: "todos_db"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - golang_test
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "todos"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret"

    volumes:
      - golang_test:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  grpc:
    container_name: "grpc"
    build:
      context: .
      dockerfile: service.Dockerfile
    ports:
      - "4040:4040"
    restart: on-failure
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "todos"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret"
    depends_on:
      - db
    volumes:
      - .:/app/
    networks:
      - golang_test
  gateway:
    container_name: "gateway"
    build:
      context: .
      dockerfile: gateway.Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - grpc
      - db
    networks:
      - golang_test
      
networks:
  golang_test: null
volumes:
  golang_test: null
