POST  http://127.0.0.1:8080/v2/todos HTTP/1.1
Content-Type: application/json

{
   "todo":{
      "id":2,
      "title":"dasdas",
      "description":"asdasdasd",
      "createAt":"2020-01-15T01:30:15.01Z",
      "updateAt":"2020-01-15T01:30:15.01Z",
      "status":2,
      "tags":["sleep", "relax"]
   }
}

###

GET http://127.0.0.1:8080/v2/todos?pag=100&tags=Sleep&tags=relax&status=2  HTTP/1.1
Content-Type: application/json




###
GET http://127.0.0.1:8080/v2/todos/2 HTTP/1.1
Content-Type: application/json

###
DELETE http://127.0.0.1:8080/v2/todos/2 HTTP/1.1

###
PUT  http://127.0.0.1:8080/v2/todos HTTP/1.1
Content-Type: application/json

{
  "api": "v2",
  "todo": {
    "id": 2,
    "title": "duckhue01",
    "description": "duckhue01",
    "createAt": "2020-01-15T01:30:15Z",
    "updateAt": "2020-01-15T01:30:15Z",
    "tags": [
      "relax",
      "sleep"
    ],
    "status": "TODO",
    "order": 3
  }
}

###

PUT  http://127.0.0.1:8080/v2/todos/reorder/17 HTTP/1.1
Content-Type: application/json

{
   "api":"v2",
   "pos":-100
}